NUT-3192 port nutrio reporter to our gem
nutrio/minitest-reporters pull request #1
Opened 2016-12-15 19:38 UTC by midwire

Ported our old nutrio minitest reporter to the gem and modified the report line with better time outputs according to specs in the NUT-3192 ticket. The gem itself does not test the custom reporters and I did not add tests for ours either but I've manually tested it with our test runs.

2016-12-15 19:44 UTC, trak3r requested changes

2016-12-15 19:44 UTC, trak3r commented on lib/minitest/reporters/nutrio_reporter.rb
> +class NutrioReporter < Minitest::Reporters::BaseReporter
there seems to be a LOT of boilerplate code in this file.
was it copied from somewhere else?
could we just subclass that source instead?

2016-12-15 19:46 UTC, midwire commented on lib/minitest/reporters/nutrio_reporter.rb
> +class NutrioReporter < Minitest::Reporters::BaseReporter
yeah, i copied this from https://github.com/nutrio/services/blob/NUT-3076-elastic-delta-indexing-for-meals/test/nutrio_minitest_reporter.rb

I can certainly clean it up

2016-12-15 19:54 UTC, trak3r commented on lib/minitest/reporters/nutrio_reporter.rb
> +class NutrioReporter < Minitest::Reporters::BaseReporter
> I can certainly clean it up

please remove everything that isn't specific to our needs, which i believe is merely the time formatting.

2016-12-15 20:16 UTC, midwire commented on lib/minitest/reporters/nutrio_reporter.rb
> +class NutrioReporter < Minitest::Reporters::BaseReporter
Much cleaner now.

2016-12-15 20:38 UTC, trak3r requested changes

2016-12-15 20:38 UTC, trak3r commented on lib/minitest/reporters/nutrio_reporter.rb
> +        hours = seconds / 3600
is this math necessary? can't just use strftime() ?

2016-12-15 21:22 UTC, midwire commented on lib/minitest/reporters/nutrio_reporter.rb
> +        hours = seconds / 3600
We can use `strftime`. I did that initially but realized that for a total_time like 128 seconds it will print something like `00:02:08` or in whatever format we want but there will always be a '00' for hours if the time is less than an hour, etc. '%H:%M:%S'. We could tell it to not zero-pad values but there will still be a single '0' for Hour and Minute where appropriate. LMK if thats ok and i'll change it.

2016-12-15 21:55 UTC, trak3r commented on lib/minitest/reporters/nutrio_reporter.rb
> +        hours = seconds / 3600
> there will always be a '00' for hours 

i'm ok with that

2016-12-16 17:44 UTC, midwire commented on lib/minitest/reporters/nutrio_reporter.rb
> +        hours = seconds / 3600
cool. here's a screenshot:

![1__cblackburn_transwarp_local__bash_](https://cloud.githubusercontent.com/assets/178386/21272456/f84ca238-c384-11e6-8732-e6f71dd94c05.jpg)

2016-12-16 18:03 UTC, trak3r approved these changes

2016-12-16 18:03 UTC, trak3r commented
@midwire you need to remove nutrio as a reviewer for this to be merged

2016-12-16 18:05 UTC, midwire commented
> you need to remove nutrio as a reviewer for this to be merged

done.

2016-12-16 18:08 UTC, merged